org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G
android.useAndroidX=true
android.enableJetifier=true
# Отключаем lint для быстрой сборки
android.lintOptions.checkReleaseBuilds=false
android.lintOptions.abortOnError=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.daemon.jvm.options=-Xmx2G
